version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: DOC_Database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Santiago32411
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Spring Boot Application
  spring-app:
    image: spring-boot-docker.jar:latest
    container_name: DOC_SpringBoot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Santiago32411
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: